config/routes.rb
Rails.application.routes.draw do
  resources :inquiries do
  end
   resources  :financial_advisors do
   end

  root 'inquiries#index'
  
  get 'dashboard' => 'inquiries#new'
  get "summary" => "inquiries#show"
  get  "financial_advisors" => "inquiries#edit"

end

app/models/financial_advisor.rb
class FinancialAdvisor < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/financial_advisors_controller.rb
class FinancialAdvisorsController < ApplicationController
  def new
  @financial_advisors = Financial_Advisors.new
  end

  def index
    @financial_advisors = Financial_Advisors.all
  end

  def show
    @financial_advisors = Financial_Advisors.find params[:id]
  end


  def edit
    @Financial_Advisors = FinancialAdvisors.find params[:id]
  end

  def create
  @Financial_Advisors = Financial_Advisors.create( financial_advisor_params )
  end

  private

  # Use strong_parameters for attribute whitelisting
  # Be sure to update your create() and update() controller methods.

  def financial_advisor_params
  params.require(:Financial_Advisor).permit(:avatar)
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController

  def new
    @inquiry = Inquiry.new
  end

  def create
    inquiry = Inquiry.create(inquiry_params)
    redirect_to inquiry_path(inquiry)
  end

  def show
    @inquiry = Inquiry.find params[:id]
  end

  def index
    render layout: 'splash'
  end

  # def edit
  #   @Financial_Advisors = FinancialAdvisor.all
  # end

  private

  def inquiry_params
    params.require(:inquiry).permit(:service, :age, :status, :home, :job, :salary)
  end
  
  # def create
  # @Financial_Advisors = Financial_Advisor.create( financial_advisor_params )
  # end

  # private

  # # Use strong_parameters for attribute whitelisting
  # # Be sure to update your create() and update() controller methods.

  # def financial_advisor_params
  # params.require(:Financial_Advisor).permit(:avatar)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/financial_advisors_helper.rb
module FinancialAdvisorsHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/financial_advisors/new.html.erb
<%= form_for @Financial_Advisors, url: financial_advisors_path, html: { multipart: true } do |form| %>
  <%= form.file_field :avatar %>
<% end %>

app/views/inquiries/edit.html.erb
<h1>New Financial_Advisor</h1>

<% @Financial_Advisors.each do |finAd| %>
  <%= finAd.name %>
  <br>
<% end %>
<%= link_to 'Back', financial_advisors_path %>

app/views/inquiries/index.html.erb
<div class="wallstreet-bull">
 <!-- <img src = "WALL-STREET-BULL.JPG"> --> 
 <img src = "/assets/2461095922_0d7d414a3e_o.jpg" style = "width:110vw; height 110vh";>


<!-- <div>
<button class="take_charge" type="submit">Take Charge of your finances</button>
</div> -->

app/views/inquiries/new.html.erb
         <!-- Fixed navbar -->
      

   
    <div class="myform-container">
      <%= form_for @inquiry do |f| %>
   
        <div class = "financial" id = "help">
         <label> What kind of financial help are you seeking?</label>
         <div>
         <input type = "radio" name = "inquiry[service]"  value = "Financial Advisor"> Financial Advisor
         </div>
          <input type = "radio" name = "inquiry[service]"  value = "Estate Planning"> Estate Planning
          <div>
          <input type = "radio" name =  "inquiry[service]" value = "CPA"> CPA/Tax Preparer/Accountant
          </div>
           <div>
           <input type = "radio" name = "inquiry[service]" value = "Financial Advisor"> Bookkeeper
           </div>

           <div class = "age" id = "current_age">
           <label>What is your current age?</label>
           <input type = "number" name = "inquiry[age]" min = "18" max = "120">
          </div>
          <div class = "status" id = "relationship"></div>
          <label> What situation best describe you?</label>
         <div>
          <input type = "radio" name = "inquiry[status]" value ="Single"> Single <br>
          </div>
         <div>
        <input type = "radio" name = "inquiry[status]" value = "Single with dependents"> Single with dependents
       </div>
      <div>
       <input type = "radio" name = "inquiry[status]" value = "Married"> Married
      </div>
         <div>
       <input type = "radio" name = "inquiry[status]" value = "Married with dependents"> Married with dependents
      </div>
      <div class = "home" id="owner">
      <label>Are you a home owner?</label>
      <input type = "radio" name = "inquiry[home]" value = "yes"> Yes
      <input type = "radio" name = "inquiry[home]" value = "No"> No
    </div>
    <div class ="job" id = "work">
      <label>What is your current Occupation?</label>
        <input type = "text" name = "inquiry[job]">
    <div class = "salary" id = "money">
        <label>What is your current after-tax income?
          <input type = "number" name = "inquiry[salary]" min = "1" max = "120000000", placeholder="$">
    </div>

     <button class = "Submit"> Submit</button>

    </form>

   
  <% end %>

 </div>






  

app/views/inquiries/show.html.erb
<div class = "FinancialSummary">
  <p>FinancialSummary Page</p>
  <p>Service Requested: <%= @inquiry.service %></p>
  <p>How old are you? <%= @inquiry.age %></p>
  <p>What situation best describe you? <%= @inquiry.status %></p>
  <p>Are you a homeowner? <%= @inquiry.home %></p>
  <p>What is your occupation:<%= @inquiry.job %></p>
  <p>What is your current income? <%= @inquiry.salary %></p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wealthczar</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
           <!--  <button type="button" class="btn btn-default" aria-label="Left Align">
            <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span> 
            </button> -->

              <!-- <button type="button" class="btn btn-default btn-lg"> -->
   
            <span class="glyphicon glyphicon-king" aria-hidden="true"></span>
              <!-- </button> -->
            <!-- <a class="navbar-brand" href="#">Wealth Czar</a> -->
          </div>
        <div><a class="navbar-brand" href="/">Wealth Czar</a></div>
        <div class = "questions"> <a>Questions? contact us?<a></div>
      </nav>

<div class="financial-district">

  <%= yield %>
</div>

</body>
</html>

app/views/layouts/splash.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wealthczar</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
      <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed-inverse" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="glyphicon glyphicon-king " aria-hidden="true"></span>
     </div>
      <div><a class="navbar-brand" href="/">Wealth Czar</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1-inverse">
      <ul class="nav navbar-nav">
           <li><a href="/">Home</a></li>
                 <li><a href="/dashboard">Dashboard</a></li>
                          <li><a href="/financial_advisors">Financial Advisors</a></li>
                             <li><a href="contact.html">Contact Us</a></li>
      </ul>

     <div class = "nav navbar-right ">
     <a href="/dashboard" class ="btn btn-success btn-md" style = "margin-top:10px;" type="submit">Get Started</a>
      </div>  
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


  <%= yield %>

  <div class="about">
  <div class="container">
    <div class="row">
      <h2>How Wealth Czar Works</h2>
      <div class="col-md-4">
          <p>1. Input your information</p>
            
           <p> Tell us about yourself and your unique financial situation.</p>
      </div><!-- end div .col-md-4 -->
      <div class="col-md-4">
        <p>2. Get Advice</p>
         <p> We will compile your financial information and recommend powerful financial products tailored to your needs.</p>
      </div><!-- end div .col-md-4 -->
      <div class="col-md-4">
        <p>3. Get Matched and Relax</p>
          <p>You will be matched with or you will able to choose from our list of experienced and qualified financial advisors to take care of all your financial needs.</p>

              <a href="/dashboard" class="btn btn-success btn-lg" type="submit">Get Started</a>

      </div><!-- end div .col-md-4 -->
    </div><!-- end div .row -->
  </div><!-- end .container -->
</div><!-- end .about -->


</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>